#!/usr/bin/env bash
# Mirror the frontend, supabase/migrations, and supabase/functions from the
# cloned Lovable repo (../closercontrolleadintel) into this deploy repo.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${SRC:-$ROOT/../closercontrolleadintel}"

test -d "$SRC" || { echo "missing: $SRC"; exit 1; }

log() { echo "[sync] $*"; }

log "mirroring frontend (apps/web/)"
mkdir -p "$ROOT/apps/web"
rsync -a --delete \
  --exclude=node_modules \
  --exclude=dist \
  --exclude=.git \
  --exclude=backups \
  --exclude=.env \
  --exclude=.env.local \
  "$SRC/" "$ROOT/apps/web/"

log "mirroring supabase/migrations (Lovable's 30 Lead Intel migrations)"
mkdir -p "$ROOT/supabase/migrations"
rsync -a --delete "$SRC/supabase/migrations/" "$ROOT/supabase/migrations/"

log "mirroring supabase/functions (29 edge functions + _shared/)"
mkdir -p "$ROOT/supabase/functions"
# Mirror from the Lovable repo's supabase/functions/. Lead Intel's export also
# stores them at backups/backend-export/edge-functions/ — use the live ones.
if [ -d "$SRC/supabase/functions" ]; then
  rsync -a --delete "$SRC/supabase/functions/" "$ROOT/supabase/functions/"
else
  rsync -a --delete "$SRC/backups/backend-export/edge-functions/" "$ROOT/supabase/functions/"
fi

log "creating main router for supabase/edge-runtime"
mkdir -p "$ROOT/supabase/functions/main"
cat > "$ROOT/supabase/functions/main/index.ts" <<'TS'
// Main router for supabase/edge-runtime.
// One worker per function via EdgeRuntime.userWorkers (no dynamic imports —
// Lovable functions call Deno.serve() at module scope).
//
// Auto-regenerated by scripts/sync-from-lovable-repo.sh.

// @ts-ignore
declare const EdgeRuntime: any;

console.log("[main] booting router");

Deno.serve(async (req: Request) => {
  const url = new URL(req.url);
  const segments = url.pathname.replace(/^\/+/, "").split("/");
  const serviceName = segments[0];

  if (!serviceName) {
    return new Response(
      JSON.stringify({ msg: "missing function name in request" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }

  const servicePath = `/home/deno/functions/${serviceName}`;

  try {
    const envVars = Object.entries(Deno.env.toObject());
    const worker = await EdgeRuntime.userWorkers.create({
      servicePath,
      memoryLimitMb: 256,
      workerTimeoutMs: 5 * 60 * 1000,
      cpuTimeSoftLimitMs: 10_000,
      cpuTimeHardLimitMs: 30_000,
      noModuleCache: false,
      importMapPath: null,
      envVars,
    });
    return await worker.fetch(req);
  } catch (e) {
    const msg = (e && (e as Error).message) || String(e);
    if (msg.includes("Module not found") || msg.includes("ENOENT") || msg.includes("failed to read path")) {
      return new Response(
        JSON.stringify({ msg: `unknown function: ${serviceName}` }),
        { status: 404, headers: { "Content-Type": "application/json" } },
      );
    }
    console.error(`[main] error in ${serviceName}:`, msg);
    return new Response(
      JSON.stringify({ msg }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }
});
TS

log "done. Next: docker compose build && docker compose up -d"
