SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

# Top-level orchestrator for the Phase 1 verification stack:
#   - platform-launcher  on :8080
#   - acq-coach          on :3000 (frontend) and :54321 (API)
#   - leadintel          on :3001 (frontend) and :54322 (API)

LAUNCHER  := platform-launcher
ACQ       := acq-coach-selfhost
LEADINTEL := leadintel-selfhost

help:  ## Show this help
	@awk 'BEGIN{FS=":.*##"} /^[a-zA-Z_-]+:.*##/{printf "  \033[36m%-22s\033[0m %s\n",$$1,$$2}' $(MAKEFILE_LIST)

# ---------- one-shot setup ----------

setup:  ## First-time setup: copy .env.example → .env in both selfhost dirs and generate secrets
	@for dir in $(ACQ) $(LEADINTEL); do \
	  if [ ! -f "$$dir/.env" ]; then \
	    cp "$$dir/.env.example" "$$dir/.env"; \
	    echo "" >> "$$dir/.env"; \
	    echo "# === Auto-generated by 'make setup' ===" >> "$$dir/.env"; \
	    bash "$$dir/docker/gen-keys.sh" >> "$$dir/.env"; \
	    echo "[setup] wrote $$dir/.env (you still need to delete the CHANGE_ME lines and set per-fn API keys)"; \
	  else \
	    echo "[setup] $$dir/.env already exists, skipping"; \
	  fi; \
	done

# ---------- build + run ----------

sync:  ## Re-mirror both Lovable repos into the selfhost dirs (picks up AppSwitcher etc.)
	cd $(ACQ)       && ./scripts/sync-from-lovable-repo.sh
	cd $(LEADINTEL) && ./scripts/sync-from-lovable-repo.sh

build:  ## Build all 3 stacks (launcher + acq + leadintel)
	cd $(LAUNCHER)  && docker compose build
	cd $(ACQ)       && docker compose build
	cd $(LEADINTEL) && docker compose build

up:  ## Start all 3 stacks (assumes images already built)
	cd $(LAUNCHER)  && docker compose up -d
	cd $(ACQ)       && docker compose up -d
	cd $(LEADINTEL) && docker compose up -d
	@echo ""
	@echo "  Launcher:   http://localhost:8080"
	@echo "  ACQ:        http://localhost:3100   API: http://localhost:54421"
	@echo "  Lead Intel: http://localhost:3101   API: http://localhost:54422"

down:  ## Stop all 3 stacks (KEEP volumes)
	-cd $(LAUNCHER)  && docker compose down
	-cd $(ACQ)       && docker compose down
	-cd $(LEADINTEL) && docker compose down

nuke:  ## Stop + remove containers AND volumes (DESTROYS local DBs)
	-cd $(LAUNCHER)  && docker compose down -v
	-cd $(ACQ)       && docker compose down -v
	-cd $(LEADINTEL) && docker compose down -v

restart: down up  ## Restart everything

# ---------- data restore ----------

restore-acq:        ## Restore ACQ data from backups/migration-export/
	cd $(ACQ) && ./scripts/restore-from-lovable.sh

restore-leadintel:  ## Restore Lead Intel data from backups/backend-export/
	cd $(LEADINTEL) && ./scripts/restore-from-lovable.sh

restore: restore-acq restore-leadintel  ## Restore both projects

# ---------- logs / debug ----------

logs:                ## Tail all 3 stacks (split panes recommended)
	@echo "Use: docker logs -f <container>"
	@echo "  platform-launcher"
	@echo "  acq-coach        acq-edge"
	@echo "  leadintel        leadintel-edge"

logs-acq:            ## Tail ACQ main + edge
	docker logs -f acq-coach &
	docker logs -f acq-edge

logs-leadintel:      ## Tail Lead Intel main + edge
	docker logs -f leadintel &
	docker logs -f leadintel-edge

ps:                  ## Show all containers
	@docker ps --filter name=platform-launcher --filter name=acq-coach --filter name=acq-edge --filter name=leadintel --filter name=leadintel-edge --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

psql-acq:            ## psql into the ACQ database
	$(MAKE) -C $(ACQ) psql

psql-leadintel:      ## psql into the Lead Intel database
	$(MAKE) -C $(LEADINTEL) psql

# ---------- verification quick checks ----------

verify:  ## Run smoke checks against all 3 stacks (after `make up`)
	@echo "[verify] launcher  → http://localhost:8080/health"
	@curl -fsS http://localhost:8080/health || echo " (FAIL)"
	@echo "[verify] acq API    → http://localhost:54421/health"
	@curl -fsS http://localhost:54421/health || echo " (FAIL)"
	@echo "[verify] acq auth   → http://localhost:54421/auth/v1/health"
	@curl -fsS http://localhost:54421/auth/v1/health || echo " (FAIL)"
	@echo "[verify] leadintel API  → http://localhost:54422/health"
	@curl -fsS http://localhost:54422/health || echo " (FAIL)"
	@echo "[verify] leadintel auth → http://localhost:54422/auth/v1/health"
	@curl -fsS http://localhost:54422/auth/v1/health || echo " (FAIL)"
