#!/usr/bin/env bash
# Mirror the frontend, supabase/migrations, and supabase/functions from the
# cloned Lovable repo (../my-acq-coach-5b771b53) into this deploy repo.
# Re-run after any change in the Lovable repo (or when Lovable emits new code).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${SRC:-$ROOT/../my-acq-coach-5b771b53}"

test -d "$SRC" || { echo "missing: $SRC"; exit 1; }

log() { echo "[sync] $*"; }

log "mirroring frontend (apps/web/)"
mkdir -p "$ROOT/apps/web"
rsync -a --delete \
  --exclude=node_modules \
  --exclude=dist \
  --exclude=.git \
  --exclude=backups \
  --exclude=.env \
  --exclude=.env.local \
  "$SRC/" "$ROOT/apps/web/"

log "mirroring supabase/migrations (Lovable's 28 ACQ migrations)"
mkdir -p "$ROOT/supabase/migrations"
rsync -a --delete "$SRC/supabase/migrations/" "$ROOT/supabase/migrations/"

log "mirroring supabase/functions (9 edge functions + _shared/)"
mkdir -p "$ROOT/supabase/functions"
rsync -a --delete "$SRC/supabase/functions/" "$ROOT/supabase/functions/"

log "creating main router for supabase/edge-runtime"
mkdir -p "$ROOT/supabase/functions/main"
cat > "$ROOT/supabase/functions/main/index.ts" <<'TS'
// Main router for supabase/edge-runtime.
// Spawns one isolated worker per function via EdgeRuntime.userWorkers.
// Do NOT use dynamic imports — Lovable functions call Deno.serve() at module
// scope so importing them would clobber the main process.
//
// Auto-regenerated by scripts/sync-from-lovable-repo.sh.

// @ts-ignore -- EdgeRuntime is a global inside supabase/edge-runtime
declare const EdgeRuntime: any;

console.log("[main] booting router");

Deno.serve(async (req: Request) => {
  const url = new URL(req.url);
  const segments = url.pathname.replace(/^\/+/, "").split("/");
  const serviceName = segments[0];

  if (!serviceName) {
    return new Response(
      JSON.stringify({ msg: "missing function name in request" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }

  const servicePath = `/home/deno/functions/${serviceName}`;

  try {
    const envVars = Object.entries(Deno.env.toObject());
    const worker = await EdgeRuntime.userWorkers.create({
      servicePath,
      memoryLimitMb: 256,
      workerTimeoutMs: 5 * 60 * 1000,
      cpuTimeSoftLimitMs: 10_000,
      cpuTimeHardLimitMs: 30_000,
      noModuleCache: false,
      importMapPath: null,
      envVars,
    });
    return await worker.fetch(req);
  } catch (e) {
    const msg = (e && (e as Error).message) || String(e);
    if (msg.includes("Module not found") || msg.includes("ENOENT") || msg.includes("failed to read path")) {
      return new Response(
        JSON.stringify({ msg: `unknown function: ${serviceName}` }),
        { status: 404, headers: { "Content-Type": "application/json" } },
      );
    }
    console.error(`[main] error in ${serviceName}:`, msg);
    return new Response(
      JSON.stringify({ msg }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }
});
TS

log "done. Run 'docker compose build && docker compose up -d' next."
