#!/usr/bin/env bash
# Fan .env.vps out into the six per-project .env files the compose stack needs.
#
#   bash scripts/write-project-envs.sh
#
# Why this exists: each project's docker-compose.yml declares `env_file: .env`
# and interpolates ${VARS} with project-local names (POSTGRES_PASSWORD,
# ANON_KEY, JWT_SECRET, ...). The top-level .env.vps uses prefixed names
# (ACQ_POSTGRES_PASSWORD, ...) so one file can hold all six projects' secrets
# without collisions. This script does the prefixed → unprefixed mapping and
# writes each project's .env. Re-run it any time you edit .env.vps.
#
# Extra secrets not in gen-vps-secrets.sh output (PLATFORM_APP_PASSWORD,
# PLATFORM_ADMIN_PASSWORD, PLATFORM_AUTH_ADMIN_PASSWORD, CRON_SECRET) are
# generated on first run and APPENDED to .env.vps so they stay stable.

set -euo pipefail

BASE_DIR="${BASE_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
ENV_VPS="$BASE_DIR/.env.vps"

if [ ! -f "$ENV_VPS" ]; then
  echo "ERROR: $ENV_VPS not found. Run: cp .env.vps.example .env.vps && bash scripts/gen-vps-secrets.sh" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a; source "$ENV_VPS"; set +a

# ─── Generate-if-missing extras, append to .env.vps for stability ────────────
gen_if_missing() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    local val
    val=$(openssl rand -hex 24)
    printf '%s=%s\n' "$name" "$val" >> "$ENV_VPS"
    export "$name=$val"
    echo "[write-envs] generated $name (appended to .env.vps)"
  fi
}
gen_if_missing PLATFORM_APP_PASSWORD
gen_if_missing PLATFORM_ADMIN_PASSWORD
gen_if_missing PLATFORM_AUTH_ADMIN_PASSWORD
gen_if_missing CRON_SECRET

# Required values — fail loudly rather than write blank passwords.
for required in JWT_SECRET TOKEN_ENCRYPTION_KEY PLATFORM_POSTGRES_PASSWORD \
                ACQ_POSTGRES_PASSWORD ACQ_AUTHENTICATOR_PASSWORD ACQ_AUTH_ADMIN_PASSWORD \
                ACQ_ANON_KEY ACQ_SERVICE_ROLE_KEY \
                LEADINTEL_POSTGRES_PASSWORD LEADINTEL_AUTHENTICATOR_PASSWORD \
                LEADINTEL_AUTH_ADMIN_PASSWORD LEADINTEL_ANON_KEY LEADINTEL_SERVICE_ROLE_KEY \
                LAUNCHER_HOST ACQ_HOST ACQ_API_HOST LEADINTEL_HOST LEADINTEL_API_HOST; do
  if [ -z "${!required:-}" ] || [[ "${!required}" == PASTE_FROM_GEN_SECRETS ]]; then
    echo "ERROR: $required is unset or still a placeholder in .env.vps" >&2
    exit 1
  fi
done

LAUNCHER_URL="https://$LAUNCHER_HOST"
ACQ_URL="${ACQ_URL:-https://$ACQ_HOST}"
ACQ_API_URL="${ACQ_API_URL:-https://$ACQ_API_HOST}"
LEADINTEL_URL="${LEADINTEL_URL:-https://$LEADINTEL_HOST}"
LEADINTEL_API_URL="${LEADINTEL_API_URL:-https://$LEADINTEL_API_HOST}"
PLATFORM_AUTH_URL="${PLATFORM_AUTH_URL:-$LAUNCHER_URL/auth}"

# ─── platform-db/.env ────────────────────────────────────────────────────────
cat > "$BASE_DIR/platform-db/.env" <<EOF
# Generated by scripts/write-project-envs.sh from .env.vps — do not edit by hand.
POSTGRES_PASSWORD=$PLATFORM_POSTGRES_PASSWORD
PLATFORM_APP_PASSWORD=$PLATFORM_APP_PASSWORD
PLATFORM_ADMIN_PASSWORD=$PLATFORM_ADMIN_PASSWORD
PLATFORM_AUTH_ADMIN_PASSWORD=$PLATFORM_AUTH_ADMIN_PASSWORD
EOF

# ─── platform-auth/.env ──────────────────────────────────────────────────────
cat > "$BASE_DIR/platform-auth/.env" <<EOF
# Generated by scripts/write-project-envs.sh from .env.vps — do not edit by hand.
PLATFORM_JWT_SECRET=$JWT_SECRET
PLATFORM_AUTH_ADMIN_PASSWORD=$PLATFORM_AUTH_ADMIN_PASSWORD
SITE_URL=$LAUNCHER_URL
API_EXTERNAL_URL=$LAUNCHER_URL/auth
EOF

# ─── platform-admin-api/.env ─────────────────────────────────────────────────
cat > "$BASE_DIR/platform-admin-api/.env" <<EOF
# Generated by scripts/write-project-envs.sh from .env.vps — do not edit by hand.
PLATFORM_ADMIN_DB_URL=postgres://platform_admin:$PLATFORM_ADMIN_PASSWORD@platform-db:5432/platform
TOKEN_ENCRYPTION_KEY=$TOKEN_ENCRYPTION_KEY
ACQ_DB_URL=postgres://postgres:$ACQ_POSTGRES_PASSWORD@acq-coach:5432/acqcoach
LEADINTEL_DB_URL=postgres://postgres:$LEADINTEL_POSTGRES_PASSWORD@leadintel:5432/leadintel
EOF

# ─── platform-launcher/.env ──────────────────────────────────────────────────
cat > "$BASE_DIR/platform-launcher/.env" <<EOF
# Generated by scripts/write-project-envs.sh from .env.vps — do not edit by hand.
LAUNCHER_HOST=$LAUNCHER_HOST
ACQ_URL=$ACQ_URL
ACQ_API_URL=$ACQ_API_URL
ACQ_ANON_KEY=$ACQ_ANON_KEY
LEADINTEL_URL=$LEADINTEL_URL
LEADINTEL_API_URL=$LEADINTEL_API_URL
LEADINTEL_ANON_KEY=$LEADINTEL_ANON_KEY
PLATFORM_AUTH_URL=$PLATFORM_AUTH_URL
PLATFORM_DB_URL=postgres://platform_app:$PLATFORM_APP_PASSWORD@platform-db:5432/platform
PLATFORM_ADMIN_DB_URL=postgres://platform_admin:$PLATFORM_ADMIN_PASSWORD@platform-db:5432/platform
EOF

# ─── acq-coach-selfhost/.env ─────────────────────────────────────────────────
cat > "$BASE_DIR/acq-coach-selfhost/.env" <<EOF
# Generated by scripts/write-project-envs.sh from .env.vps — do not edit by hand.
PUBLIC_HOST=$ACQ_HOST
PUBLIC_API_HOST=$ACQ_API_HOST
SITE_URL=$ACQ_URL
VITE_SUPABASE_URL=$ACQ_API_URL
VITE_SUPABASE_PUBLISHABLE_KEY=$ACQ_ANON_KEY
VITE_SUPABASE_PROJECT_ID=acqcoach-selfhost
VITE_PAYMENTS_CLIENT_TOKEN=
VITE_OTHER_APP_URL=$LEADINTEL_URL
VITE_OTHER_APP_NAME=Lead Intel
VITE_LAUNCHER_URL=$LAUNCHER_URL

POSTGRES_DB=acqcoach
POSTGRES_PASSWORD=$ACQ_POSTGRES_PASSWORD
AUTHENTICATOR_PASSWORD=$ACQ_AUTHENTICATOR_PASSWORD
AUTH_ADMIN_PASSWORD=$ACQ_AUTH_ADMIN_PASSWORD

JWT_SECRET=$JWT_SECRET
ANON_KEY=$ACQ_ANON_KEY
SERVICE_ROLE_KEY=$ACQ_SERVICE_ROLE_KEY

GOTRUE_DISABLE_SIGNUP=${GOTRUE_DISABLE_SIGNUP:-true}
GOTRUE_MAILER_AUTOCONFIRM=${GOTRUE_MAILER_AUTOCONFIRM:-true}
GOTRUE_URI_ALLOW_LIST=$ACQ_URL,$ACQ_URL/*,$LAUNCHER_URL,$LAUNCHER_URL/*
GOTRUE_EXTERNAL_GOOGLE_ENABLED=false
GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=
GOTRUE_EXTERNAL_GOOGLE_SECRET=
GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=$ACQ_API_URL/auth/v1/callback

OPENAI_API_KEY=${OPENAI_API_KEY:-}
DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
STRIPE_TEST_SECRET_KEY=
STRIPE_TEST_PUBLISHABLE_KEY=
STRIPE_TEST_WEBHOOK_SECRET=
STRIPE_LIVE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
STRIPE_LIVE_PUBLISHABLE_KEY=
STRIPE_LIVE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
CRON_SECRET=$CRON_SECRET

PLATFORM_DB_URL=postgres://platform_app:$PLATFORM_APP_PASSWORD@platform-db:5432/platform
EOF

# ─── leadintel-selfhost/.env ─────────────────────────────────────────────────
cat > "$BASE_DIR/leadintel-selfhost/.env" <<EOF
# Generated by scripts/write-project-envs.sh from .env.vps — do not edit by hand.
PUBLIC_HOST=$LEADINTEL_HOST
PUBLIC_API_HOST=$LEADINTEL_API_HOST
SITE_URL=$LEADINTEL_URL
VITE_SUPABASE_URL=$LEADINTEL_API_URL
VITE_SUPABASE_PUBLISHABLE_KEY=$LEADINTEL_ANON_KEY
VITE_SUPABASE_PROJECT_ID=leadintel-selfhost
VITE_OTHER_APP_URL=$ACQ_URL
VITE_OTHER_APP_NAME=ACQ Coach
VITE_LAUNCHER_URL=$LAUNCHER_URL

POSTGRES_DB=leadintel
POSTGRES_PASSWORD=$LEADINTEL_POSTGRES_PASSWORD
AUTHENTICATOR_PASSWORD=$LEADINTEL_AUTHENTICATOR_PASSWORD
AUTH_ADMIN_PASSWORD=$LEADINTEL_AUTH_ADMIN_PASSWORD

JWT_SECRET=$JWT_SECRET
ANON_KEY=$LEADINTEL_ANON_KEY
SERVICE_ROLE_KEY=$LEADINTEL_SERVICE_ROLE_KEY

GOTRUE_DISABLE_SIGNUP=${GOTRUE_DISABLE_SIGNUP:-true}
GOTRUE_MAILER_AUTOCONFIRM=${GOTRUE_MAILER_AUTOCONFIRM:-true}
GOTRUE_URI_ALLOW_LIST=$LEADINTEL_URL,$LEADINTEL_URL/*,$LAUNCHER_URL,$LAUNCHER_URL/*
GOTRUE_EXTERNAL_GOOGLE_ENABLED=false
GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=
GOTRUE_EXTERNAL_GOOGLE_SECRET=
GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=$LEADINTEL_API_URL/auth/v1/callback

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY:-}
STRIPE_TEST_SECRET_KEY=
STRIPE_TEST_PUBLISHABLE_KEY=
STRIPE_TEST_WEBHOOK_SECRET=
STRIPE_LIVE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
STRIPE_LIVE_PUBLISHABLE_KEY=
STRIPE_LIVE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
CRON_SECRET=$CRON_SECRET

GHL_PIT_TOKEN=
GHL_LOCATION_ID=

PLATFORM_DB_URL=postgres://platform_app:$PLATFORM_APP_PASSWORD@platform-db:5432/platform
EOF

chmod 600 "$BASE_DIR"/platform-db/.env "$BASE_DIR"/platform-auth/.env \
          "$BASE_DIR"/platform-admin-api/.env "$BASE_DIR"/platform-launcher/.env \
          "$BASE_DIR"/acq-coach-selfhost/.env "$BASE_DIR"/leadintel-selfhost/.env

echo "[write-envs] wrote 6 project .env files:"
for f in platform-db platform-auth platform-admin-api platform-launcher acq-coach-selfhost leadintel-selfhost; do
  echo "  ✓ $f/.env ($(grep -c '=' "$BASE_DIR/$f/.env") vars)"
done
