// Main router for supabase/edge-runtime.
// One worker per function, spawned on demand via EdgeRuntime.userWorkers.
// Standard pattern from supabase/edge-runtime examples.
//
// Auto-regenerated by scripts/sync-from-lovable-repo.sh.

// @ts-ignore -- EdgeRuntime is a global inside supabase/edge-runtime
declare const EdgeRuntime: any;

console.log("[main] booting router");

Deno.serve(async (req: Request) => {
  const url = new URL(req.url);
  const segments = url.pathname.replace(/^\/+/, "").split("/");
  const serviceName = segments[0];

  if (!serviceName) {
    return new Response(
      JSON.stringify({ msg: "missing function name in request" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }

  const servicePath = `/home/deno/functions/${serviceName}`;

  try {
    const envVars = Object.entries(Deno.env.toObject());

    const worker = await EdgeRuntime.userWorkers.create({
      servicePath,
      memoryLimitMb: 256,
      workerTimeoutMs: 5 * 60 * 1000,
      noModuleCache: false,
      importMapPath: null,
      envVars,
    });

    return await worker.fetch(req);
  } catch (e) {
    const msg = (e && (e as Error).message) || String(e);
    if (
      msg.includes("Module not found") ||
      msg.includes("ENOENT") ||
      msg.includes("failed to read path")
    ) {
      return new Response(
        JSON.stringify({ msg: `unknown function: ${serviceName}` }),
        { status: 404, headers: { "Content-Type": "application/json" } },
      );
    }
    console.error(`[main] error in ${serviceName}:`, msg);
    return new Response(
      JSON.stringify({ msg }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }
});
