// Main router for supabase/edge-runtime.
// Spawns one isolated worker per function via EdgeRuntime.userWorkers.
// Do NOT use dynamic imports — Lovable functions call Deno.serve() at module
// scope so importing them would clobber the main process.
//
// Auto-regenerated by scripts/sync-from-lovable-repo.sh.

// @ts-ignore -- EdgeRuntime is a global inside supabase/edge-runtime
declare const EdgeRuntime: any;

console.log("[main] booting router");

// ─── Master Keys overlay ────────────────────────────────────────────────
// Pull editable platform-wide keys (OPENAI / STRIPE / ...) from platform-db
// on each request (60s cache) and overlay them onto the worker's envVars.
// This is how UI changes in Platform Admin take effect without restarts.
// Deployment .env values STILL serve as fallback when a master key is unset.
import postgres from "npm:postgres@3.4.5";
const PLATFORM_DB_URL = Deno.env.get("PLATFORM_DB_URL") ?? "";
const sql = PLATFORM_DB_URL
  ? postgres(PLATFORM_DB_URL, { max: 2, idle_timeout: 30, connect_timeout: 5, prepare: false })
  : null;

let masterCache: Record<string, string> | null = null;
let masterExp = 0;

async function getMasterKeys(): Promise<Record<string, string>> {
  if (masterCache && Date.now() < masterExp) return masterCache;
  if (!sql) { masterCache = {}; masterExp = Date.now() + 60_000; return masterCache; }
  try {
    const rows = await sql<{ key_name: string; key_value: string }[]>`
      SELECT key_name, key_value FROM platform.master_keys
    `;
    masterCache = Object.fromEntries(rows.map(r => [r.key_name, r.key_value]));
  } catch (e) {
    console.error("[main] master_keys load failed:", (e as Error).message);
    masterCache = masterCache ?? {};
  }
  masterExp = Date.now() + 60_000;
  return masterCache;
}

Deno.serve(async (req: Request) => {
  const url = new URL(req.url);
  const segments = url.pathname.replace(/^\/+/, "").split("/");
  const serviceName = segments[0];

  if (!serviceName) {
    return new Response(
      JSON.stringify({ msg: "missing function name in request" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }

  const servicePath = `/home/deno/functions/${serviceName}`;

  try {
    // Build envVars = container env + DB master_keys overlay.
    // DB wins: if a key exists in both, the UI-managed value is used.
    // Container env stays as the source of truth for non-editable infra vars
    // (DB URLs, JWT_SECRET, service role keys, etc.).
    const containerEnv = Deno.env.toObject();
    const master = await getMasterKeys();
    const merged = { ...containerEnv, ...master };
    // Per-app Stripe webhook secrets: the master_keys table is shared by both
    // apps, but webhook signing secrets are per-endpoint. The UI stores them
    // app-prefixed; each app's router claims its own prefix here.
    if (merged["LEADINTEL_STRIPE_TEST_WEBHOOK_SECRET"]) merged["STRIPE_TEST_WEBHOOK_SECRET"] = merged["LEADINTEL_STRIPE_TEST_WEBHOOK_SECRET"];
    if (merged["LEADINTEL_STRIPE_LIVE_WEBHOOK_SECRET"]) merged["STRIPE_LIVE_WEBHOOK_SECRET"] = merged["LEADINTEL_STRIPE_LIVE_WEBHOOK_SECRET"];

    const envVars = Object.entries(merged);
    const worker = await EdgeRuntime.userWorkers.create({
      servicePath,
      memoryLimitMb: 256,
      workerTimeoutMs: 5 * 60 * 1000,
      cpuTimeSoftLimitMs: 10_000,
      cpuTimeHardLimitMs: 30_000,
      noModuleCache: false,
      importMapPath: null,
      envVars,
    });
    return await worker.fetch(req);
  } catch (e) {
    const msg = (e && (e as Error).message) || String(e);
    if (msg.includes("Module not found") || msg.includes("ENOENT") || msg.includes("failed to read path")) {
      return new Response(
        JSON.stringify({ msg: `unknown function: ${serviceName}` }),
        { status: 404, headers: { "Content-Type": "application/json" } },
      );
    }
    console.error(`[main] error in ${serviceName}:`, msg);
    return new Response(
      JSON.stringify({ msg }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }
});

